BASE: ['']
TOOLBOX_MODE: "train_and_test"  # "train_and_test" or "only_train" or "only_test"
TRAIN:
  BATCH_SIZE: 4
  EPOCHS: 10
  LR: 1e-3
  MODEL_FILE_NAME: UBFC-rPPG_FactorizePhys_FSAM_Res_BNN
  PLOT_LOSSES_AND_LR: True
  DATA:
    FS: 30
    DATASET: UBFC-rPPG
    DO_PREPROCESS: False                    # if first time, should be true
    DATA_FORMAT: NCDHW
    DATA_PATH: "/kaggle/input/ubfc-rppg-dataset"                     # Raw dataset path, need to be updated
    CACHED_PATH: ""    # Processed dataset save path, need to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.0
    END: 0.25
    PREPROCESS:
      DATA_TYPE: ['Raw']
      DATA_AUG: ['None']    # 'None' or 'Motion' is supported, used if the data path points to an augmented dataset or requires augmentation
      LABEL_TYPE: Standardized
      DO_CHUNK: True
      CHUNK_LENGTH: 160
      CROP_FACE:
        DO_CROP_FACE: True
        BACKEND: 'Y5F'    # HC for Haar Cascade, Y5F for YOLO5Face
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: True
          DYNAMIC_DETECTION_FREQUENCY : 30
          USE_MEDIAN_FACE_BOX: False    # This should be used ONLY if dynamic detection is used
      RESIZE:
        H: 72
        W: 72
VALID:
  DATA:
    FS: 30
    DATASET: UBFC-rPPG
    DO_PREPROCESS: False                    # if first time, should be true
    DATA_FORMAT: NCDHW
    DATA_PATH: "/kaggle/input/ubfc-rppg-dataset"                     # Raw dataset path, need to be updated
    CACHED_PATH: ""    # Processed dataset save path, need to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.25
    END: 0.50
    PREPROCESS:
      DATA_TYPE: ['Raw']
      DATA_AUG: ['None']    # 'None' or 'Motion' is supported, used if the data path points to an augmented dataset or requires augmentation
      LABEL_TYPE: Standardized
      DO_CHUNK: True
      CHUNK_LENGTH: 160
      CROP_FACE:
        DO_CROP_FACE: True
        BACKEND: 'Y5F'    # HC for Haar Cascade, Y5F for YOLO5Face
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: True
          DYNAMIC_DETECTION_FREQUENCY : 30
          USE_MEDIAN_FACE_BOX: False    # This should be used ONLY if dynamic detection is used
      RESIZE:
        H: 72
        W: 72
TEST:
  METRICS: ['MAE', 'RMSE', 'MAPE', 'MACC', 'Pearson', 'SNR', 'BA']
  USE_LAST_EPOCH: True                   # to use provided validation dataset to find the best epoch, should be false
  OUTPUT_SAVE_DIR: "model_outputs/bnn_results"  # Directory to save test outputs and uncertainty visualizations
  DATA:
    FS: 30
    DATASET: PURE
    DO_PREPROCESS: true            # if first time, should be true
    DATA_FORMAT: NCDHW
    DATA_PATH: "/kaggle/input/pure-rppg-research"                     # Raw dataset path, need to be updated
    CACHED_PATH: "Cached"    # Processed dataset save path, need to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.0
    END: 0.2
    PREPROCESS:
      DATA_TYPE: ['Raw']
      LABEL_TYPE: Standardized
      DO_CHUNK: True
      CHUNK_LENGTH: 160
      CROP_FACE:
        DO_CROP_FACE: True
        BACKEND: 'Y5F'    # HC for Haar Cascade, Y5F for YOLO5Face
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: True
          DYNAMIC_DETECTION_FREQUENCY : 30
          USE_MEDIAN_FACE_BOX: False    # This should be used ONLY if dynamic detection is used
      RESIZE:
        H: 72
        W: 72
DEVICE: cuda:0
NUM_OF_GPU_TRAIN: 1
LOG:
  PATH: runs/exp
MODEL:
  DROP_RATE: 0.1
  NAME: FactorizePhys
  FactorizePhys:
    CHANNELS: 3
    FRAME_NUM: 160
    MD_FSAM: True
    MD_TYPE: "NMF"
    MD_TRANSFORM: "T_KAB"     #Default, if not specified
    MD_R: 1
    MD_S: 1
    MD_STEPS: 4
    MD_RESIDUAL: True
    MD_INFERENCE: True
    # Bayesian Neural Network parameters
    enable_bnn: True            # Enable Bayesian Neural Network
    bnn_prior_sigma_1: 1.0      # Prior sigma 1 (larger variance distribution in mixture)
    bnn_prior_sigma_2: 0.002    # Prior sigma 2 (smaller variance distribution in mixture)
    bnn_prior_pi: 0.5           # Prior mixture proportion
    bnn_kl_weight: 1e-6         # Weight for KL divergence loss term
    bnn_samples: 20             # Number of Monte Carlo samples for uncertainty estimation
INFERENCE:
  BATCH_SIZE: 4
  EVALUATION_METHOD: "FFT"        # "FFT" or "peak detection"
  EVALUATION_WINDOW:
    USE_SMALLER_WINDOW: False        # Change this if you'd like an evaluation window smaller than the test video length
    WINDOW_SIZE: 30        # In seconds
  MODEL_PATH: "" 
